version: '2'

services:
  master-app:
    image: master-app
    environment:
      APP_PORT: 8000
      APP_LEVEL: master
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: host

  secondary-app1:
    image: secondary-app1
    environment:
      APP_PORT: 8001
      APP_LEVEL: secondary
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: host

  secondary-app2:
    image: secondary-app2
    environment:
      APP_PORT: 8002
      APP_LEVEL: secondary      
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: host    